# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Gclass.create([
  { :gclass => "7a", :created_at => "2012-07-17 23:51:09", :updated_at => "2012-07-17 23:51:09" },
  { :gclass => "7b", :created_at => "2012-07-17 23:51:16", :updated_at => "2012-07-17 23:51:16" },
  { :gclass => "8a", :created_at => "2012-07-17 23:51:22", :updated_at => "2012-07-17 23:51:22" },
  { :gclass => "8b", :created_at => "2012-07-17 23:51:29", :updated_at => "2012-07-17 23:51:29" }
])



Manager.create([
  { :manager_id => 123, :name => "Aksman", :password => "123", :deadline => "2012-07-12 00:00:00", :group => 1, :created_at => "2012-07-17 23:50:10", :updated_at => "2012-07-18 00:35:30" },
  { :manager_id => 234, :name => "Ezra", :password => "234", :deadline => "2014-07-19 01:15:00", :group => 2, :created_at => "2012-07-19 01:15:48", :updated_at => "2012-07-19 01:15:48" }
])



Student.create([
  { :student_id => 987, :name => "Student ABC", :subject => "History", :gclass => "7a", :grade => 43, :note => "badd!!!", :created_at => "2012-07-18 00:04:01", :updated_at => "2012-07-18 00:36:30" },
  { :student_id => 987, :name => "Student ABC", :subject => "Math", :gclass => "7a", :grade => 99, :note => "xcv", :created_at => "2012-07-18 00:04:01", :updated_at => "2012-07-18 22:59:16" },
  { :student_id => 987, :name => "Student ABC", :subject => "SaaS", :gclass => "7a", :grade => 65, :note => "yjhjh", :created_at => "2012-07-18 00:15:26", :updated_at => "2012-07-19 00:44:55" },
  { :student_id => 876, :name => "Student BCE", :subject => "History", :gclass => "7a", :grade => 100, :note => "excellent work", :created_at => "2012-07-18 00:16:14", :updated_at => "2012-07-18 00:36:30" },
  { :student_id => 876, :name => "Student BCE", :subject => "Math", :gclass => "7a", :grade => 78, :note => "", :created_at => "2012-07-18 00:16:14", :updated_at => "2012-07-18 22:59:16" },
  { :student_id => 876, :name => "Student BCE", :subject => "SaaS", :gclass => "7a", :grade => 100, :note => "hghg", :created_at => "2012-07-18 00:16:14", :updated_at => "2012-07-19 00:44:55" },
  { :student_id => 111, :name => "Pupil A", :subject => "SaaS", :gclass => "8b", :grade => nil, :note => nil, :created_at => "2012-07-18 00:30:21", :updated_at => "2012-07-18 00:30:21" },
  { :student_id => 222, :name => "Pupil B", :subject => "SaaS", :gclass => "8b", :grade => nil, :note => nil, :created_at => "2012-07-18 00:31:02", :updated_at => "2012-07-18 00:31:02" },
  { :student_id => 111, :name => "Pupil A", :subject => "History", :gclass => "8b", :grade => 56, :note => "yes!1", :created_at => "2012-07-18 00:31:25", :updated_at => "2012-07-18 22:21:30" },
  { :student_id => 222, :name => "Pupil B", :subject => "History", :gclass => "8b", :grade => nil, :note => "", :created_at => "2012-07-18 00:31:25", :updated_at => "2012-07-18 22:02:32" },
  { :student_id => 333, :name => "Pupil C", :subject => "History", :gclass => "8b", :grade => nil, :note => "", :created_at => "2012-07-18 00:32:03", :updated_at => "2012-07-18 22:02:32" },
  { :student_id => 333, :name => "Pupil C", :subject => "SaaS", :gclass => "8b", :grade => nil, :note => nil, :created_at => "2012-07-18 00:32:03", :updated_at => "2012-07-18 00:32:03" },
  { :student_id => 111, :name => "Pupil A", :subject => "Math", :gclass => "8b", :grade => nil, :note => nil, :created_at => "2012-07-18 20:47:31", :updated_at => "2012-07-18 20:47:31" },
  { :student_id => 222, :name => "Pupil B", :subject => "Math", :gclass => "8b", :grade => nil, :note => nil, :created_at => "2012-07-18 20:47:31", :updated_at => "2012-07-18 20:47:31" },
  { :student_id => 333, :name => "Pupil C", :subject => "Math", :gclass => "8b", :grade => nil, :note => nil, :created_at => "2012-07-18 20:47:31", :updated_at => "2012-07-18 20:47:31" },
  { :student_id => 765, :name => "Stud CDE", :subject => "History", :gclass => "7a", :grade => nil, :note => nil, :created_at => "2012-07-18 23:53:10", :updated_at => "2012-07-18 23:53:10" },
  { :student_id => 765, :name => "Stud CDE", :subject => "Math", :gclass => "7a", :grade => nil, :note => nil, :created_at => "2012-07-18 23:53:10", :updated_at => "2012-07-18 23:53:10" },
  { :student_id => 765, :name => "Stud CDE", :subject => "SaaS", :gclass => "7a", :grade => 56, :note => "dfdf", :created_at => "2012-07-18 23:53:10", :updated_at => "2012-07-19 00:44:55" },
  { :student_id => 565, :name => "AAA AAA", :subject => "History", :gclass => "7b", :grade => nil, :note => nil, :created_at => "2012-07-19 00:43:01", :updated_at => "2012-07-19 00:43:01" },
  { :student_id => 565, :name => "AAA AAA", :subject => "Math", :gclass => "7b", :grade => nil, :note => nil, :created_at => "2012-07-19 00:43:01", :updated_at => "2012-07-19 00:43:01" },
  { :student_id => 454, :name => "BBB", :subject => "History", :gclass => "7b", :grade => nil, :note => nil, :created_at => "2012-07-19 00:43:19", :updated_at => "2012-07-19 00:43:19" },
  { :student_id => 454, :name => "BBB", :subject => "Math", :gclass => "7b", :grade => nil, :note => nil, :created_at => "2012-07-19 00:43:19", :updated_at => "2012-07-19 00:43:19" },
  { :student_id => 787, :name => "CCC", :subject => "History", :gclass => "7b", :grade => nil, :note => nil, :created_at => "2012-07-19 00:43:58", :updated_at => "2012-07-19 00:43:58" },
  { :student_id => 787, :name => "CCC", :subject => "Math", :gclass => "7b", :grade => nil, :note => nil, :created_at => "2012-07-19 00:43:58", :updated_at => "2012-07-19 00:43:58" }
])



Subject.create([
  { :subject => "History", :created_at => "2012-07-17 23:51:46", :updated_at => "2012-07-17 23:51:46" },
  { :subject => "Math", :created_at => "2012-07-17 23:51:57", :updated_at => "2012-07-17 23:51:57" },
  { :subject => "English", :created_at => "2012-07-17 23:52:04", :updated_at => "2012-07-17 23:52:04" },
  { :subject => "SaaS", :created_at => "2012-07-17 23:52:10", :updated_at => "2012-07-17 23:52:10" },
  { :subject => "Literature", :created_at => "2012-07-19 01:19:41", :updated_at => "2012-07-19 01:19:41" }
])



Teacher.create([
  { :teacher_id => 2345, :name => "Moshe Levy", :subject => "History", :gclass => "7a", :password => "2345", :group => 1, :created_at => "2012-07-17 23:52:48", :updated_at => "2012-07-18 00:36:30", :date_of_submission => "2012-07-18", :submitted => true },
  { :teacher_id => 3456, :name => "Yoram Katz", :subject => "Math", :gclass => "7a", :password => "3456", :group => 1, :created_at => "2012-07-17 23:53:32", :updated_at => "2012-07-18 22:59:16", :date_of_submission => "2012-07-18", :submitted => true },
  { :teacher_id => 2345, :name => "Moshe Levy", :subject => "History", :gclass => "7b", :password => "2345", :group => 1, :created_at => "2012-07-17 23:54:00", :updated_at => "2012-07-17 23:54:00", :date_of_submission => nil, :submitted => false },
  { :teacher_id => 3456, :name => "Yoram Katz", :subject => "Math", :gclass => "7b", :password => "3456", :group => 1, :created_at => "2012-07-17 23:54:13", :updated_at => "2012-07-17 23:54:13", :date_of_submission => nil, :submitted => false },
  { :teacher_id => 4567, :name => "Reuven Yagel", :subject => "SaaS", :gclass => "7a", :password => "4567", :group => 1, :created_at => "2012-07-18 00:15:26", :updated_at => "2012-07-19 00:44:55", :date_of_submission => "2012-07-19", :submitted => true },
  { :teacher_id => 4567, :name => "Reuven Yagel", :subject => "SaaS", :gclass => "8b", :password => "4567", :group => 1, :created_at => "2012-07-18 00:23:31", :updated_at => "2012-07-18 00:23:31", :date_of_submission => nil, :submitted => false },
  { :teacher_id => 2345, :name => "Moshe Levy", :subject => "History", :gclass => "8b", :password => "2345", :group => 1, :created_at => "2012-07-18 00:31:25", :updated_at => "2012-07-18 22:21:30", :date_of_submission => "2012-07-18", :submitted => true },
  { :teacher_id => 6789, :name => "Radel Ben-Av", :subject => "Math", :gclass => "8b", :password => "6789", :group => 1, :created_at => "2012-07-18 20:47:31", :updated_at => "2012-07-18 20:47:31", :date_of_submission => nil, :submitted => false },
  { :teacher_id => 2345, :name => "Moshe Levy", :subject => "History", :gclass => "8a", :password => "2345", :group => 1, :created_at => "2012-07-18 22:22:34", :updated_at => "2012-07-18 22:22:34", :date_of_submission => nil, :submitted => false },
  { :teacher_id => 9999, :name => "Michael Michaeli", :subject => "Literature", :gclass => "8a", :password => "9999", :group => 2, :created_at => "2012-07-19 01:20:35", :updated_at => "2012-07-19 01:20:35", :date_of_submission => nil, :submitted => false }
])


